junk_brands = {
    "traškučiai": [
        "Lays",
        "Lay's",
        "Pringles",
        "Estrella",
        "Doritos",
        "Taffel",
        "Cheetos",
        "Pringles",
        "Chio",
    ],
    "saldumynai": [
        "Kinder",
        "Milka",
        "Snickers",
        "Mars",
        "Twix",
        "Bounty",
        "Haribo",
        "Candy Pop",
        "Trolli",
        "Vidal",
        "Fini",
        "Mentos",
        "Tic Tac",
        "Chupa Chups",
        "Orbit",
        "Hubba Bubba",
        "M&M",
        "Mms",
        "Skittles",
        "Roshen",
        "Fazer",
        "Merci",
        "Toffifee",
        "Raffaello",
        "Ferrero",
        "Nutella",
        "Pergalė",
        "Rūta",
        "Nidar",
        "Karūna",
    ],
    "gėrimai": [
        "Coca Cola",
        "Coca-Cola",
        "Coca C0la",
        "Pepsi",
        "Fanta",
        "Sprite",
        "Red Bull",
        "Monster",
        "Battery",
        "Dynamit",
        "Prime",
        "Oshee",
        "Nestea",
        "Lipton",
        "Dr Pepper",
        "Schweppes",
    ],
    "kepiniai": ["7 Days", "7days", "Magija", "Mantinga", "Biržų duona", "Gardėsis"],
    "perdirbta_mėsa": ["Biovela", "Klaipėdos maistas", "Samsonas", "Krekenavos"],
    "loterija": ["Teleloto", "Vikinglotto", "Eurojackpot", "Kenoloto", "Jėga", "Superloto"],
}

junk_words = [
    # Užkandžiai
    "traškučiai",
    "traskuciai",
    "čipsai",
    "cipsai",
    "nachos",
    "spragėsiai",
    "spragesiai",
    "popkornas",
    "sūrūs užkandžiai",
    "surus uzkandziai",
    "kukurūzų traškučiai",
    "kukuruzu traskuciai",
    "sūrio skonio",
    "surio skonio",
    "cheese balls",
    "krekeriai",
    "trapučiai",
    "trapuciai",

    # Saldumynai
    "šokoladas",
    "sokoladas",
    "saldainiai",
    "guminukai",
    "guminukas",
    "guminukų",
    "guminuku",
    "guminukais",
    "meškiukai",
    "meskiukai",
    "meškiukas",
    "meskiukas",
    "gummy",
    "gummies",
    "želė saldainiai",
    "zele saldainiai",
    "želė",
    "zele",
    "ledinukai",
    "ledinukas",
    "čiulpinukai",
    "ciulpinukai",
    "batonėlis",
    "batonelis",
    "karamelė",
    "karamele",
    "kramtomoji guma",
    "guma",

    # Sausainiai ir desertai
    "sausainiai",
    "vafliai",
    "pyragas",
    "pyragai",
    "tortas",
    "keksas",
    "keksiukas",
    "desertas",
    "ledai",
    "ledų",
    "ledu",
    "plombyras",
    "šerbetas",
    "serbetas",

    # Bandelės ir saldūs kepiniai
    "bandelė",
    "bandeles",
    "bandelės",
    "bandelių",
    "bandeliu",
    "bandelė su varške",
    "bandele su varske",
    "bandelė su cinamonu",
    "bandele su cinamonu",
    "cinamoninė bandelė",
    "cinamonine bandele",
    "cinamonas",
    "kruasanas",
    "kruasanai",
    "croissant",
    "spurga",
    "spurgos",
    "donut",
    "pyragėlis",
    "pyragelis",
    "pynė",
    "pyne",
    "bandelė su šokoladu",
    "bandele su sokoladu",
    "bandelė su obuoliais",
    "bandele su obuoliais",
    "bandelė su kremu",
    "bandele su kremu",

    # Greitas maistas
    "pica",
    "burgeris",
    "mėsainis",
    "mesainis",
    "kebabas",
    "dešrainis",
    "desrainis",
    "hot dog",
    "bulvytės fri",
    "bulvytes fri",
    "fri bulvytės",
    "fri bulvytes",
    "vištienos kepsneliai",
    "vistienos kepsneliai",
    "nuggets",

    # Perdirbta mėsa
    "dešrelės",
    "desreles",
    "dešrelė",
    "desrele",
    "dešra",
    "desra",
    "saliamis",
    "saliami",
    "rūkytos dešrelės",
    "rukytos desreles",

    # Saldūs, gazuoti ir energiniai gėrimai
    "limonadas",
    "gazuotas gėrimas",
    "gazuotas gerimas",
    "gėrimas coca",
    "gerimas coca",
    "kola",
    "cola",
    "c0la",
    "fanta",
    "sprite",
    "pepsi",
    "energinis gėrimas",
    "energinis gerimas",
    "energetinis",
    "red bull",
    "monster",
    "sultys",
    "nektaras",

    # Alkoholis
    "alus",
    "sidras",
    "degtinė",
    "degtine",
    "vynas",
    "likeris",
    "kokteilis",

    # Loterija
    "loterija",
    "bilietas",
    "bilietai",
    "loto",
    "teleloto",
    "vikinglotto",
    "eurojackpot",
    "kenoloto",
    "jėga",
    "jega",
    "superloto",
    "nutrinamas",
    "nutrink",
    "scratch",
]
